{
 "title": "CDX and S3",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CC CDX latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time, t_static, t_first, t_second, t_first_miss, t_second_miss from timing\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time ASC\n",
     "rawQueryText": "SELECT time, t_static, t_first, t_second, t_first_miss, t_second_miss from timing\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "AWS Open Data latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time, t_s3, t_s3_miss from timing\nWHERE time >= 1683395855222 / 1000 and time < 1683417455222 / 1000\nORDER BY time ASC\n",
     "rawQueryText": "SELECT time, t_s3, t_s3_miss from timing\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CC CDX errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT time, cdx_timeout, cdx_connection_error, cdx_slow_down, cdx_unknown from errors\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time ASC\n",
     "rawQueryText": "SELECT time, cdx_timeout, cdx_connection_error, cdx_slow_down, cdx_unknown from errors\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "AWS Open Data errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT time, s3_timeout, s3_connection_error, s3_slow_down, s3_unknown from errors\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time ASC\n",
     "rawQueryText": "SELECT time, s3_timeout, s3_connection_error, s3_slow_down, s3_unknown from errors\nWHERE time >= $__from / 1000 and time < $__to / 1000\nORDER BY time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}